version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todoapp       
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # só libera quando banco está REALMENTE pronto
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: todo-web
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: todoapp
      DB_USER: postgres
      DB_PASS: senha123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge