services:
  # Load Balancer (Nginx)
  nginx:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app-network

  # Instância 1 
  app1:
    build: ./app
    container_name: app-server-1
    hostname: app-server-1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Instância 2
  app2:
    build: ./app
    container_name: app-server-2
    hostname: app-server-2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Instância 3 
  app3:
    build: ./app
    container_name: app-server-3
    hostname: app-server-3
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge